# Generated by Django 5.1.2 on 2024-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='remainder',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
